version: 2

models:
  - name: stg_raw__sales
    tests:
      - unique:
          column_name: "(pk)"
  - name: int_campaigns
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date_date
            - campaign_key
  - name: int_campaigns_day
    tests:
     - unique:
         column_name: date_date
